"""empty message

Revision ID: 29d4ae5c89b3
Revises: 4350b9f080a6
Create Date: 2024-11-19 00:41:42.915036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d4ae5c89b3'
down_revision = '4350b9f080a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('course_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('course_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('course_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('course_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
