"""Add grade to Enrollment

Revision ID: 4350b9f080a6
Revises: c5781e6bf9de
Create Date: 2024-11-17 17:48:15.469976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4350b9f080a6'
down_revision = 'c5781e6bf9de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)

    # ### end Alembic commands ###
